# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfd2a31a9ab534a7ebcae8a9b3ca7a9e6e0c7e4056a5c9e9a9f5e66372b8e18a748071049b615e0fd2121b4c98a5c3f5d9744b40e7737debe71b4140e2ef4e33

test:
  secret_key_base: f8b9c1928320577f026c76860943f02b6d40a26ad07d7177e90a0c5fa874b64a0c00d61b350bb96d07cdad378543d0d8fe78133d700582bc8d200a8d0aacdc94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
